language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 8
  - 9

before_script:
  - yarn build

after_success:
  - yarn travis-deploy-once "yarn semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
